site_name: LeaderBoard
repo_url: https://github.com/Rakesh-Seenu/test_leader
repo_name: VPE/LeaderBoard

docs_dir: docs

theme:
  name: "material"
  logo: assets/images/VPE.png
  # custom_dir: docs/overrides
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - navigation.instant0
    - navigation.path
    - navigation.instant.prefetch
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
  font:
    code: Roboto Mono
  favicon: assets/images/VPE.png
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: custom
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dark
      primary: custom
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  # icon:
  #   logo: vpe/VPE
  #   repo: fontawesome/brands/github      

extra_css:
  - assets/css/color-schemes.css
  - assets/css/fonts.css
  - assets/css/custom-material.css

plugins:
  - search
  # - gen-files:
  #   scripts:
  #     - scripts/gen_ref_pages.py
  - macros
  - mike:
      alias_type: copy
      canonical_version: "latest"
      version_selector: true
      css_dir: "assets/css"
      javascript_dir: "assets/js"
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ./docs/
  - mkdocs-jupyter:
      theme: auto
      highlight_extra_classes: "jupyter-notebook"
  - include_dir_to_nav:
      file_pattern: '.*\.(md|ipynb)$'
  - literate-nav:
      nav_file: docs/SUMMARY.md    
  - site-urls

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
      restrict_base_path: False
      base_path: "."
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - admonition
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Rakesh-Seenu/test_leader
  version:
    provider: mike
    default: latest
    alias: true
  # docker_url: nvcr.io/nvidia/clara/bionemo-framework
  # docker_tag: nightly
  github_url: https://github.com/Rakesh-Seenu/test_leader

copyright: |
  &copy; Copyright 2025-2026,VPE Inc. All rights reserved.

extra:
  pwa: false
